### ISSUE TITLE
0x52 - OlympusTreasury#removeCategoryGroup fails to properly clear the categorization which can lead to incorrect asset categorization

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-11-olympus-judging#158]
0x52

medium

# OlympusTreasury#removeCategoryGroup fails to properly clear the categorization which can lead to incorrect asset categorization

## Summary

The categorization mapping in OlympusTreasury is used to track which assets are associated with which category groups. When removing a categoryGroup, the categorization array is never properly cleared. This leaves a tangled and potentially hazardous mapping. In the even the category is added again, it could lead to incorrect valuation when deploying RBS.

## Vulnerability Detail

[OlympusTreasury.sol#L657-L667](https://github.com/sherlock-audit/2023-11-olympus/blob/main/bophades/src/modules/TRSRY/OlympusTreasury.sol#L657-L667)

    function categorize(address asset_, Category category_) external override permissioned {
        // Check that asset is initialized
        if (!assetData[asset_].approved) revert TRSRY_InvalidParams(0, abi.encode(asset_));

        // Check if the category exists by seeing if it has a non-zero category group
        CategoryGroup group = categoryToGroup[category_];
        if (fromCategoryGroup(group) == bytes32(0)) revert TRSRY_CategoryDoesNotExist(category_);

        // Store category data for address
        categorization[asset_][group] = category_;
    }

Above we see that when an asset is categorized, it is added to the categorization mapping. This mapping is essential for determining which assets are in which category.

[OlympusTreasury.sol#L567-L583](https://github.com/sherlock-audit/2023-11-olympus/blob/main/bophades/src/modules/TRSRY/OlympusTreasury.sol#L567-L583)

    function removeCategoryGroup(CategoryGroup group_) external override permissioned {
        // Check if the category group exists
        if (!_categoryGroupExists(group_)) revert TRSRY_CategoryGroupDoesNotExist(group_);

        // Remove category group
        uint256 len = categoryGroups.length;
        for (uint256 i; i < len; ) {
            if (fromCategoryGroup(categoryGroups[i]) == fromCategoryGroup(group_)) {
                categoryGroups[i] = categoryGroups[len - 1];
                categoryGroups.pop();
                break;
            }
            unchecked {
                ++i;
            }
        }

Inside OlympusTreasury#removeCategoryGroup we can see that even though the categoryGroup is removed, the assets are never cleared from it. This can lead to issues down the line. As an example, if a the category is re-added at a later date, it may contain assets that are no longer supported or have since been re-categorized. This could lead to invalid protocol metrics that cause RBS (or other future modules) funds to be deployed incorrectly  

## Impact

Incorrect protocol metrics leading polices to function incorrectly

## Code Snippet

[OlympusTreasury.sol#L567-L583](https://github.com/sherlock-audit/2023-11-olympus/blob/main/bophades/src/modules/TRSRY/OlympusTreasury.sol#L567-L583)

## Tool used

Manual Review

## Recommendation

Clear the categorization of every asset associated with that categoryGroup

**Comment by securitygrid** [comment]
Escalate
This issue assumes that the administrator made a mistake about call order. According to Sherlock's rules, this is not valid. `removeCategory` is a behavior that should be performed after ensuring that all assets have called `uncategorize`.

**Comment by sherlock-admin2** [comment]
> Escalate
> This issue assumes that the administrator made a mistake about call order. According to Sherlock's rules, this is not valid. `removeCategory` is a behavior that should be performed after ensuring that all assets have called `uncategorize`.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Agree with @securitygrid, this issue should be invalid.

**Comment by 0xrusowsky** [comment]
https://github.com/OlympusDAO/bophades/pull/252

**Comment by IAm0x52** [comment]
Fix looks good. Now clears the categorization mapping as well.

**Comment by Arabadzhiew** [comment]
> Escalate This issue assumes that the administrator made a mistake about call order. According to Sherlock's rules, this is not valid. `removeCategory` is a behavior that should be performed after ensuring that all assets have called `uncategorize`.

Just FYI, this function will most likely be executed through a governance proposal on the Governance contract, which is different from the protocol admin (the OlympusDAO multi-sig).
`In Olympus V3, the Kernel's owner will be the Governance (Policy) contract.`  [Source - the OlympusDAO docs](https://docs.olympusdao.finance/main/technical/overview/#ownership-model-the-executor)

**Comment by Czar102** [comment]
Planning to accept the escalation and consider this issue an informational one.

**Comment by Czar102** [comment]
Result:
Low
Has duplicates

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-11-olympus-judging/issues/158/#issuecomment-1882418333): accepted
