### ISSUE TITLE
rvierdiiev - UniswapV3OracleHelper.getTWAPRatio will show incorrect price for negative ticks

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-11-olympus-judging#38]
rvierdiiev

high

# UniswapV3OracleHelper.getTWAPRatio will show incorrect price for negative ticks

## Summary
UniswapV3OracleHelper.getTWAPRatio will show incorrect price for negative ticks, because getTimeWeightedTick function doesn't round up for negative ticks
## Vulnerability Detail
`UniswapV3OracleHelper.getTWAPRatio` function is used by protocol [to validate price deviation in the `BunniPrice`](https://github.com/sherlock-audit/2023-11-olympus-rvierdiyev/blob/main/bophades/src/modules/PRICE/submodules/feeds/BunniPrice.sol#L249-L252) and also [by `UniswapV3Price.getTokenTWAP` function](https://github.com/sherlock-audit/2023-11-olympus-rvierdiyev/blob/main/bophades/src/modules/PRICE/submodules/feeds/UniswapV3Price.sol#L154-L160).

Function itself calls [`getTimeWeightedTick` function](https://github.com/sherlock-audit/2023-11-olympus-rvierdiyev/blob/main/bophades/src/libraries/UniswapV3/Oracle.sol#L147) to get twap price tick using uniswap oracle. `getTimeWeightedTick` [uses `pool.observe` to get `tickCumulatives` array](https://github.com/sherlock-audit/2023-11-olympus-rvierdiyev/blob/main/bophades/src/libraries/UniswapV3/Oracle.sol#L85C28-L85C43) which is then used to calculate `timeWeightedTick`. 

The problem is that in case if `tickCumulatives[1] - tickCumulatives[0]` is negative, then `timeWeightedTick` should be rounded down [as it's done in the uniswap library](https://github.com/Uniswap/v3-periphery/blob/main/contracts/libraries/OracleLibrary.sol#L36).

As result, in case if `tickCumulatives[1] - tickCumulatives[0]` is negative and `(tickCumulatives[1] - tickCumulatives[0]) % secondsAgo != 0`, then returned `timeWeightedTick` will be bigger then it should be, which opens possibility for some price manipulations and arbitrage opportunities.
## Impact
In case if `tickCumulatives[1] - tickCumulatives[0]` is negative and `((tickCumulatives[1] - tickCumulatives[0]) % secondsAgo != 0`, then returned `timeWeightedTick` will be bigger then it should be.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Add this line.
`if (tickCumulatives[1] - tickCumulatives[0] < 0 && (tickCumulatives[1] - tickCumulatives[0]) % secondsAgo != 0) timeWeightedTick --;`

**Comment by securitygrid** [comment]
Escalate
This is low. I didn't sumbit this issue. 0.01% price deviation cannot be arbitraged since this price is TWAP.

**Comment by sherlock-admin2** [comment]
> Escalate
> This is low. I didn't sumbit this issue. 0.01% price deviation cannot be arbitraged since this price is TWAP.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xrusowsky** [comment]
https://github.com/OlympusDAO/bophades/pull/258

**Comment by nevillehuang** [comment]
A deviation is still a deviation, and can still be arbitraged given a large sum of funds owned by any multiple user. This would depend on if sherlock views this as "material", can agree that it is low-medium severity.

**Comment by securitygrid** [comment]
The UniswapV3 pool is [OHM-WETH](https://etherscan.io/address/0x88051b0eea095007d3bef21ab287be961f3d8598). The latest OHM is $11.6525, let’s assume the price is a bit higher: $20.

The number of OHM in the pool is 172,801e18, and the number of WETH is 735e18. We assume that the giant whale has 200,000e18 OHM for arbitrage (valued at $20*200,000=$4,000,000), and 0.01% of $20 is $0.002, then his total profit is: 200,000 * 0.002 = $400.
If you deduct the gas on the mainnet, it’s less than $400.
Let's consider using $4,000,000 to make less than $400. That's not practical.

Furthermore, token0=OHM, token1=WETH of this POOL. When will current tick be negative? That's when OHM is more expensive than WETH.

**Comment by nevillehuang** [comment]
@rvierdiyev any comments? If not I will have to agree with @securitygrid.

**Comment by rvierdiiev** [comment]
hey @nevillehuang @securitygrid 
i have to say that i even didn't think about that from such point of view
i just saw incorrect implementation and realized that twap will be affected in some conditions

as for me this issue meets these criterias, as it still can happen
> There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost.

> Causes a loss of funds but requires certain external conditions or specific states.

but i should say again, that i didn't think about it as deep as @securitygrid did and didn't try to find out which token will be token0/token1 in the pool

**Comment by IAm0x52** [comment]
Fix looks good. Now matches the Uni V3 library

**Comment by Czar102** [comment]
What are the consequences of a TWAP manipulation on the system?

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-11-olympus-judging/issues/38/#issuecomment-1882372377): accepted

**Comment by rvierdiiev** [comment]
@Czar102 can you provide reason why you accepted escalation?
as you didn't provide any input

**Comment by Czar102** [comment]
@rvierdiyev you failed to answer my question on the impact of your finding. I believe @securitygrid made an argument that you failed to counter in the scope of the codebase. I couldn't wait indefinitely for your answer, so I assumed you have nothing more to say.

**Comment by rvierdiiev** [comment]
@Czar102 pls, tag me in question next time, so i understand it is addressed to me.
we didn't do full review, but only part, so sponsor should answer such question, not me.

**Comment by Czar102** [comment]
@rvierdiyev I'll tag you next time, sorry about that.
You should have asked the sponsor and made that point in your original submission as this is Watsons' role to understand what is something impacting. I even explicitly mentioned it in my message on Discord pinned in the first days of the contest:

> I would like to draw Watsons' attention to the fact that despite any impact on a view function is a low severity finding per Sherlock rules, in this contest some view functions are to be used by the wider system (not necessarily in-scope), so if the system itself (not external codebases) will be impacted, the finding may be considered valid. Such a finding needs to contain an impact description that draws conclusions in the whole system (i.e. there needs to be a loss of funds/core functionality within the system).
